apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-villa
  labels:
    app: car-villa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-villa
  template:
    metadata:
      labels:
        app: car-villa
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
